### ISSUE TITLE
Stop auto-follow on scroll

### ISSUE THREAD

**Issue by glaslos** [glaslos/ochi#20]
Outcome: Stop following new events on scroll, resume with button

When scrolling in the events list, stop following new events. There should be a button at the bottom of the events list that resumes following events.

**Comment by kbajori50** [comment]
Hello Mr. Glaslow Can you please assign me this issue
I want to fix this and contribute more to the project 
Thank you so much :)

**Comment by glaslos** [comment]
Hey, that's great, no need to assign the ticket, just start working on it :)

**Comment by sahil-ansari01** [comment]
> Hello Mr. Glaslow Can you please assign me this issue I want to fix this and contribute more to the project Thank you so much :)

Are you working on the project. Let me know how I can work on it

**Comment by glaslos** [comment]
@sahil-ansari01 feel free to give it a try. This is not limited to one person.

**Comment by shanky-ced** [comment]
@glaslos Hello sir, i got this issue while setting up the code, can you please help with this.

 `./server localhost:3000 token secret
process_begin: CreateProcess(NULL, ./server localhost:3000 token secret, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [Makefile:6: local] Error 2`

**Comment by glaslos** [comment]
Try running make build first

**Comment by shanky-ced** [comment]
> Try running make build first

tried but still got this error. 

`src/main.ts → public/build/bundle.js...
(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
google.accounts (imported by src/SOOButton.svelte, src/SOORevokeButton.svelte)
(!) Plugin typescript: @rollup/plugin-typescript: Typescript 'sourceMap' compiler option must be set to generate source maps.
created public/build/bundle.js in 2.8s
go build -o server main.go
process_begin: CreateProcess(NULL, go build -o server main.go, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [Makefile:3: build] Error 2`

**Comment by glaslos** [comment]
Do you have Golang installed?
Also it would be great if you could update the Readme with all the things you think are missing from trying to run the project 😉

**Comment by glaslos** [comment]
Do you have Golang installed?
Also it would be great if you could update the Readme with all the things you think are missing from trying to run the project 😉

**Comment by shanky-ced** [comment]
> Do you have Golang installed? Also it would be great if you could update the Readme with all the things you think are missing from trying to run the project 😉

For sure, i was planning to update it too.  

and for the error, i didn't had Golang installed but after installing i am still getting error while making build.

> # runtime/cgo
cc1.exe: sorry, unimplemented: 64-bit mode not compiled in
make: *** [Makefile:3: build] Error 1

**Comment by glaslos** [comment]
You are trying to run this on Windows?
You can also not use the backend. Just open the frontend in the browser and disable dial() and enable [test()](https://github.com/glaslos/ochi/blob/main/src/App.svelte#L100)

**Comment by shanky-ced** [comment]
> You are trying to run this on Windows? You can also not use the backend. Just open the frontend in the browser and disable dial() and enable [test()](https://github.com/glaslos/ochi/blob/main/src/App.svelte#L100)
 
@glaslos 
I tried on windows as well as on linux, 
 in case of windows, there is that backend issue and a lot of issues with mingw gcc as well that irritated me. 
in case of linux, there is an issue with relative path i guess, cause it showed me this error while making build.

> build command-line-arguments: cannot load embed: malformed module path "embed": missing dot in first path element

**Comment by shanky-ced** [comment]
@glaslos 
btw sir i have found the issue and made appropriate changes for auto scroll, if you could a suggest the position for resume button to be placed that will be a great help. currently i have positioned it near apply button on top.

**Comment by shanky-ced** [comment]
@glaslos 
sir i have generated a PR #22  from my another id regarding this issue using test dev.
Please check if i have handled the cases right so that i can plan further for readme.
