### ISSUE TITLE
Configuration button and modal

### ISSUE THREAD

**Issue by glaslos** [glaslos/ochi#24]
Add a button to open configuration to the top bar.
On click open a model to configure:
- The number of messages in the view: Currently set to 50
- Switching between `dial()` and `test()`

**Comment by vishant007** [comment]
Want to contribute to the front-end part of this project through GSOC-23, 
My Portfolio: https://vishant-n-shah.vercel.app/
Is this issue still open?

**Comment by snehalchaudhari98** [comment]
Is this issue still open? I would love to work on this

**Comment by glaslos** [comment]
@snehalchaudhari98 #38 we just merged the first version. Feel free to suggest improvements.
